PUT http://localhost:5022/breakfasts/d41d880d-b805-48d3-a059-7e4bc873da82
Content-Type: application/json

{
    "@id": "d41d880d-b805-48d3-a059-7e4bc873da82",
    "name":"Vegan SunshineEEE",
    "description":"Vegan everything! Join us for a healthy breakfast..",
    "startDateTime":"2022-04-08T08:00:00",
    "endDateTime":"2022-04-08T11:00:00",
    "savory":[
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet":[
        "Cookie"
    ]
}